version: "3"
services:

# adds fhir service
  fhir-service:
    # "hapiproject/hapi:v6.1.0"
    image: "hapiproject/hapi:latest"

    ports:
      - "8090:8080"
    volumes:
      # config
      - ./data/server:/data/hapi
    environment:
      SPRING_CONFIG_LOCATION: 'file:///data/hapi/application.yaml'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"


  hapi-fhir-postgres:
    image: postgres:9.6
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  hapi-fhir-postgres:
